Repository HyeongJun030/TMI_Project, pull requests merged in 2022-07, with the labels that each got.

#14 test
  test.html
Labels: 형준, test

#46 priceData page
  html/main-page2.html
  html/main-page3.html
  html/priceData.html
  src/styles/pricedata.css
Labels: 승현

#47 css icon img 경로 재설정
  html/ShoppingList2.html
  html/index.html
  html/main-page3.html
Labels: 승현, chore

#57 img 경로 수정
  html/main-page1.html
  html/main-page2.html
  html/main-page3.html
  html/priceData.html
  src/styles/pricedata.css
Labels: 승현, chore
